### ISSUE TITLE
[FEATURE] Faraday 2.x support

### ISSUE THREAD

**Issue by will-in-wi** [opensearch-project/opensearch-ruby#59]
The OpenSearch gem depends on Faraday 1.x, which conflicts with newer gems which require 2.x.

It seems like 2.x is largely compatible with 1.x, so it's feasible that both can be supported simultaneously.

For now, we've downgraded our application to Faraday 1.x.

Thanks for this library!

**Comment by dblock** [comment]
Faraday is never a trivial upgrade unfortunately :( PRs welcome!

**Comment by BrianHawley** [comment]
@dblock I reviewed all the changes from Faraday 1 to 2, and its use in opensearch-transport, and verified that the client code doesn't use any of the features that changed in Faraday 2. The actual http connection code is the same.

The only significant change is that the adapter gems are no longer included in Faraday 2, except the one for Net::HTTP, so you need to include the adapter gem explicitly if you want to use it. This meant that the adapter autodetection in the client couldn't assume that the adapter was defined just because the HTTP library being adapted was defined, which to be fair it shouldn't have assumed even in Faraday 1. This turns out to mostly be a documentation problem.

Also, now that the adapter gems are optional, they tend to include the adapted HTTP library as a dependency now, while in Faraday 1 they didn't, so to be compatible with both Faraday 1 and 2 you should make sure both the http gem and the adapter gem are included. These changes mostly affected the README and the spec setup code (needed to add some requires and development gems).

I made PRs for opensearch-transport 1.x (#75) and 2.x (#76). I did the PR for the 1.x gems because people still need to support OpenSearch server 1 because at least Amazon hasn't updated their service to support OpenSearch server 2 yet. Some people (presumably) need to clean up their use of deprecated features before they can upgrade anyway, and the 2.x client gems don't support the deprecated features even if they do support using the old services when using the non-deprecated features.

There is no significant behavioral change in the PRs, aside from making the HTTP library detection less likely to fail, so it should be semver compatible even for a 1.0.x or 2.0.x release.

**Comment by dblock** [comment]
@BrianHawley Amazing, thank you so much. Let's start with `main` - I made some comments, I'll keep watching for your updates.

**Comment by BrianHawley** [comment]
@VachaShah and @dblock this change doesn't remove support for Faraday 1, and doesn't affect the connection and data transfer code - I made a point of not changing any test assertions, to make sure.

However, if someone was only referencing the opensearch gem and some non-default http gem like Typhoeus, that non-default gem won't be used without adding the adapter for the gem. This shouldn't break anything in the client, but it might be an unexpected performance degradation. This is a change in the faraday gem, not opensearch, so it's debatable as to whether this breaks semver.

I don't really consider "constrains Faraday to 1.x" to be a desired feature of the opensearch-transport gem, so undoing it was worth making the PR. I made sure to keep Faraday 1 compatibility just so it wouldn't break anything, and it will still use  Faraday 1 on Ruby 2.5 (and the Ruby 2.6 or JRuby and Typhoeus combo, until the maker of faraday-typhoeus merges my PR). I'm OK either way what version gets assigned to the change, as long as it comes out in a reasonable time.

The counterargument to making this into 2.1.x and 1.1.x releases is that for something that doesn't change any intentional behavior of the opensearch-transport gem in its own codebase, it would double your maintenance effort to support 1.0.x, 1.1.x, 2.0.x, and 2.1.x. The alternative is to just let people constrain their own faraday version in their Gemfile, and save the 2.1 update for behavioral changes in the opensearch gems themselves (like opensearch server compatibility changes).
